extends Node

const ADD_PROPERTY: int = 0
const ADD_VARIABLE: int = 1
const ADD_STATE: int = 2
const ADD_ACTION: int = 3
const ADD_TRANSISTION: int = 4
const ADD_CONDITION: int = 5

const REMOVE_PROPERTY: int = 6
const REMOVE_VARIABLE: int = 7
const REMOVE_STATE: int = 8
const REMOVE_ACTION: int = 9
const REMOVE_TRANSISTION: int = 10 
const REMOVE_CONDITION: int = 11

const EDIT_PROPERTY: int = 12
const EDIT_VARIABLE: int = 13
const EDIT_STATE: int = 14
const EDIT_ACTION: int = 15
const EDIT_TRANSISTION: int = 16
const EDIT_CONDITION: int = 17

const DESCRIPTION: Dictionary = {
	ADD_PROPERTY: "ADD_PROPERTY",
	ADD_VARIABLE: "ADD_VARIABLE",
	ADD_STATE: "ADD_STATE",
	ADD_ACTION: "ADD_ACTION",
	ADD_TRANSISTION: "ADD_TRANSISTION",
	ADD_CONDITION: "ADD_CONDITION",
	REMOVE_PROPERTY: "REMOVE_PROPERTY",
	REMOVE_VARIABLE: "REMOVE_VARIABLE",
	REMOVE_STATE: "REMOVE_STATE",
	REMOVE_ACTION: "REMOVE_ACTION",
	REMOVE_TRANSISTION: "REMOVE_TRANSISTION",
	REMOVE_CONDITION: "REMOVE_CONDITION",
	EDIT_PROPERTY: "EDIT_PROPERTY",
	EDIT_VARIABLE: "EDIT_VARIABLE",
	EDIT_STATE: "EDIT_STATE",
	EDIT_ACTION: "EDIT_ACTION",
	EDIT_TRANSISTION: "EDIT_TRANSISTION",
	EDIT_CONDITION: "EDIT_CONDITION",
}
